name: sofit_modas_pdv
description: PDV Mobile — Sofit Modas. Sincronizado com o PDV Electron v12.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^3.6.0
  cloud_firestore: ^5.4.4

  # Gerenciamento de estado
  provider: ^6.1.2

  # UI
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
